### PR TITLE
Much more efficient counter batching.

### PR DESCRIPTION
**Pull request by cscheffler**

### CODE REVIEW

**Comment by philip-sterne** [comment]
Is this PR threadsafe? (i.e. is "+=" atomic?)

**Comment by philip-sterne** [comment]
Love the idea.  Great optimisation :-)
Does this mean that our updates might occur much less frequently?

**Comment by philip-sterne** [comment]
Regardless of above - we should probably get this PR into prod.  My points are pretty minor (unless we're using threading in our consumers).

+1

**Comment by cscheffler** [comment]
@philip-sterne Looks like thread-safeness is generally quite a difficult thing to achieve: http://stackoverflow.com/questions/6319207/are-lists-thread-safe#answer-6319267

**Comment by philip-sterne** [comment]
+1

**Pull request merged**
